-- =============================================
-- AZDİLİ_MOVZULAR SEED — HƏR SİNİF ÜÇÜN REAL MÖVZULAR
-- Azərbaycan dili və ədəbiyyat fənn kurikulumu (2024)
-- =============================================

TRUNCATE azdili_movzular RESTART IDENTITY;

-- ═══════════════════════════════════════════════
-- 1-Cİ SİNİF (25 mövzu)
-- ═══════════════════════════════════════════════
INSERT INTO azdili_movzular (sinif, saha, movzu_adi, movzu_izahi, saat_sayi) VALUES
(1, 'qrammatika', 'Səslər və hərflər', 'Azərbaycan əlifbasında olan səslərin və hərflərin öyrənilməsi', 3),
(1, 'qrammatika', 'Sait səslər', 'Sait səslərin növləri: qalın-incə, dodaqlanan-dodaqlanmayan', 2),
(1, 'qrammatika', 'Samit səslər', 'Samit səslərin növləri: kar-cingiltili, tək-qoşa', 2),
(1, 'qrammatika', 'Heca və vurğu', 'Sözlərin hecalara bölünməsi, vurğunun rolu', 2),
(1, 'qrammatika', 'Söz və cümlə anlayışı', 'Söz nədir, cümlə nədir, fərqləri', 2),
(1, 'qrammatika', 'Böyük hərf qaydası', 'Cümlənin əvvəlində, xüsusi adlarda böyük hərf', 2),
(1, 'qrammatika', 'Nöqtə və sual işarəsi', 'Cümlə sonunda durğu işarələri', 2),
(1, 'oxu', 'Əlifba və oxu texnikası', 'Hərfləri tanıma, hecalı oxu, sürətli oxu əsasları', 4),
(1, 'oxu', 'Nağıl oxusu və anlama', 'Sadə nağılları oxuma, baş qəhrəmanı müəyyən etmə', 3),
(1, 'oxu', 'Şeir oxusu', 'Uşaq şeirlərinin ifadəli oxunuşu', 2),
(1, 'oxu', 'Mətn və şəkil əlaqəsi', 'Şəkillərə əsasən mətn məzmununu təxmin etmə', 2),
(1, 'oxu', 'Sözün mənası', 'Tanış olmayan sözlərin mənasını kontekstdən tapmaq', 2),
(1, 'oxu', 'Antonimlər və sinonimlər', 'Əks mənalı və yaxın mənalı sözlər', 2),
(1, 'yazi', 'Hərf yazma texnikası', 'Böyük və kiçik hərflərin düzgün yazılışı', 4),
(1, 'yazi', 'Söz və cümlə yazma', 'Sözləri və sadə cümlələri yazma', 3),
(1, 'yazi', 'Köçürmə yazısı', 'Mətni dəqiq köçürmə bacarığı', 2),
(1, 'yazi', 'Diktant', 'Eşitdiyini düzgün yazma bacarığı', 2),
(1, 'yazi', 'Şəkilə görə cümlə qurma', 'Verilmiş şəklə uyğun cümlə yazma', 2),
(1, 'danisiq', 'Salamlaşma və tanışlıq', 'Salamlaşma, ayrılma, tanışlıq ifadələri', 2),
(1, 'danisiq', 'Sadə dialoq qurma', 'Sual-cavab formasında sadə danışıq', 2),
(1, 'danisiq', 'Şəkil təsviri', 'Verilmiş şəkli şifahi təsvir etmə', 2),
(1, 'danisiq', 'Nağıl danışma', 'Dinlənilmiş nağılı öz sözləri ilə danışma', 2),
(1, 'danisiq', 'Dinləmə və anlama', 'Dinlənilən mətni başa düşmə, suallarla yoxlama', 2),
(1, 'edebiyyat', 'Uşaq ədəbiyyatı nümunələri', 'Abdulla Şaiq, M.Ə.Sabir uşaq şeirləri', 2),
(1, 'edebiyyat', 'Xalq nağılları', 'Azərbaycan xalq nağılları: "Cırtdan", "Tıq-tıq xanım"', 2);

-- ═══════════════════════════════════════════════
-- 2-Cİ SİNİF (28 mövzu)
-- ═══════════════════════════════════════════════
INSERT INTO azdili_movzular (sinif, saha, movzu_adi, movzu_izahi, saat_sayi) VALUES
(2, 'qrammatika', 'Söz birləşməsi', 'İki və daha çox sözün birləşməsi, əsas və asılı söz', 2),
(2, 'qrammatika', 'Cümlə növləri (məqsəd üzrə)', 'Nəqli, sual, nida cümlələri', 2),
(2, 'qrammatika', 'İsim anlayışı', 'Əşya, canlı-cansız bildirən sözlər', 2),
(2, 'qrammatika', 'Fel anlayışı', 'Hərəkət və iş bildirən sözlər', 2),
(2, 'qrammatika', 'Sifət anlayışı', 'Əşyanın əlamətini bildirən sözlər', 2),
(2, 'qrammatika', 'Say anlayışı', 'Əşyanın sayını və sırasını bildirən sözlər', 2),
(2, 'qrammatika', 'Əvəzlik anlayışı', 'İsmin əvəzinə işlənən sözlər: mən, sən, o', 2),
(2, 'qrammatika', 'Sözün quruluşu: kök və şəkilçi', 'Sözün əsas hissəsi və əlavə hissəsi', 2),
(2, 'oxu', 'Mətn oxusu və anlama', 'Kiçik mətnləri oxuma, əsas fikri tapma', 3),
(2, 'oxu', 'Hekayə oxusu', 'Uşaq hekayələrini oxuma, hadisələrin ardıcıllığı', 2),
(2, 'oxu', 'Şeir oxusu və əzbərləmə', 'Şeirləri ifadəli oxuma, əzbərləmə üsulları', 2),
(2, 'oxu', 'Nağıl oxusu (mürəkkəb)', 'Uzun nağılları oxuma, obrazları müəyyən etmə', 2),
(2, 'oxu', 'Məlumat mətni', 'Ensiklopedik mətnlərdən məlumat alma', 2),
(2, 'oxu', 'Sözlük istifadəsi', 'Lüğətdən söz axtarma bacarığı', 2),
(2, 'yazi', 'Dialoq yazma', 'İki şəxs arasında dialoq qurma və yazma', 2),
(2, 'yazi', 'Məktub yazma', 'Şəxsi məktub formatı: müraciət, məzmun, imza', 2),
(2, 'yazi', 'Təsviri yazı', 'Fəsil, təbiət, heyvan təsviri yazma', 2),
(2, 'yazi', 'Hekayə yazma (sadə)', 'Verilmiş başlanğıca görə qısa hekayə yazma', 2),
(2, 'yazi', 'İmla qaydaları', 'Sait və samitlərin düzgün yazılışı', 2),
(2, 'yazi', 'Diktant (mürəkkəb)', 'Mürəkkəb cümlələrin diktant yazısı', 2),
(2, 'danisiq', 'Müsahibə aparmaq', 'Sual vermə və cavabı dinləmə bacarığı', 2),
(2, 'danisiq', 'Təqdimat etmə', 'Seçilmiş mövzuda qısa şifahi təqdimat', 2),
(2, 'danisiq', 'Hekayə danışma', 'Oxuduğu hekayəni öz sözləri ilə nağıl etmə', 2),
(2, 'danisiq', 'Qrup müzakirəsi', 'Mövzu haqqında qrupda fikir mübadiləsi', 2),
(2, 'edebiyyat', 'Xalq ədəbiyyatı: tapmacalar, yanıltmaclar', 'Tapmacaların həlli, yanıltmacların oxunuşu', 2),
(2, 'edebiyyat', 'Bayatılar', 'Azərbaycan bayatıları, quruluşu və mənası', 2),
(2, 'edebiyyat', 'Uşaq şeirləri (Səməd Vurğun, Mikayıl Müşfiq)', 'Görkəmli şairlərin uşaq şeirləri', 2),
(2, 'edebiyyat', 'Əxlaq hekayələri', 'Tərbiyəvi hekayələr: düzgünlük, dostluq, səbr', 2);

-- ═══════════════════════════════════════════════
-- 3-CÜ SİNİF (30 mövzu)
-- ═══════════════════════════════════════════════
INSERT INTO azdili_movzular (sinif, saha, movzu_adi, movzu_izahi, saat_sayi) VALUES
(3, 'qrammatika', 'İsmin halları', 'Adlıq, yiyəlik, yönlük, təsirlik, yerlik, çıxışlıq hallar', 3),
(3, 'qrammatika', 'Felin zamanları', 'Keçmiş, indiki, gələcək zaman formaları', 3),
(3, 'qrammatika', 'Sifətin dərəcələri', 'Azaltma və artırma dərəcələri', 2),
(3, 'qrammatika', 'Mürəkkəb sözlər', 'İki sözdən yaranan yeni sözlər', 2),
(3, 'qrammatika', 'Durğu işarələri', 'Vergül, nöqtəli vergül, iki nöqtə istifadəsi', 2),
(3, 'qrammatika', 'İsmin təki və cəmi', 'Tək və cəm formaları, cəm şəkilçiləri', 2),
(3, 'qrammatika', 'Felin şəxsə görə dəyişməsi', 'Tək və cəm şəxs formaları', 2),
(3, 'qrammatika', 'Sözün leksik mənası', 'Çoxmənalı sözlər, həqiqi və məcazi məna', 2),
(3, 'oxu', 'Bədii mətn oxusu', 'Hekayə və nağılların dərin oxusu, hadisə analizi', 3),
(3, 'oxu', 'Məlumat mətni analizi', 'Faktları tapma, əsas və əlavə məlumat', 2),
(3, 'oxu', 'Plan tutma', 'Oxunmuş mətnin planını qurmaq', 2),
(3, 'oxu', 'Xülasə çıxarma', 'Mətni qısaltma, əsas fikirləri seçmə', 2),
(3, 'oxu', 'Müəllifin məqsədi', 'Müəllif niyə bu mətni yazıb? Hədəf auditoriya', 2),
(3, 'oxu', 'Obrazların təhlili', 'Baş və ikinci dərəcəli qəhrəmanlar', 2),
(3, 'oxu', 'Müqayisəli oxu', 'İki mətni müqayisə etmə: oxşar/fərqli cəhətlər', 2),
(3, 'yazi', 'İnşa yazma: təsviri', 'Mövzuya uyğun təsviri inşa yazma', 3),
(3, 'yazi', 'İnşa yazma: hekayə', 'Hadisə ardıcıllığı ilə hekayə yazma', 2),
(3, 'yazi', 'Məktub yazma (rəsmi)', 'Rəsmi məktub formatı', 2),
(3, 'yazi', 'Elan və afiş yazma', 'Qısa məlumatlandırıcı mətn hazırlamaq', 2),
(3, 'yazi', 'Redaktə bacarığı', 'Yazılmış mətndə səhvləri tapma və düzəltmə', 2),
(3, 'danisiq', 'Mübahisə etmə qaydaları', 'Fikirlə razılaşma/razılaşmama, əsaslandırma', 2),
(3, 'danisiq', 'Hekayə nağıl etmə', 'Həyat hadisəsini ardıcıl danışma', 2),
(3, 'danisiq', 'Şeir ifadəli oxusu', 'İntonasiya, fasilə, vurğu ilə şeir oxuma', 2),
(3, 'danisiq', 'Rol oyunu', 'Verilmiş situasiyada rol oynama, dialoq qurma', 2),
(3, 'edebiyyat', 'Atalar sözləri və zərb-məsəllər', 'Xalq müdrikliyinin ifadəsi, izahı', 2),
(3, 'edebiyyat', 'Lətifələr (Molla Nəsrəddin)', 'Molla Nəsrəddin lətifələri, yumor və ibrət', 2),
(3, 'edebiyyat', 'Təmsillər', 'Heyvan obrazları vasitəsilə ibrətamiz hekayələr', 2),
(3, 'edebiyyat', 'S.S.Axundov hekayələri', 'Süleyman Sani Axundovun uşaq hekayələri', 2),
(3, 'edebiyyat', 'A.Şaiq yaradıcılığı', 'Abdulla Şaiqin nağıl və şeirləri', 2),
(3, 'edebiyyat', 'Xalq dastanları (giriş)', 'Dastanların quruluşu, "Kitabi-Dədə Qorqud" haqqında', 2);

-- ═══════════════════════════════════════════════
-- 4-CÜ SİNİF (30 mövzu)
-- ═══════════════════════════════════════════════
INSERT INTO azdili_movzular (sinif, saha, movzu_adi, movzu_izahi, saat_sayi) VALUES
(4, 'qrammatika', 'Söz yaradıcılığı', 'Düzəltmə və mürəkkəb sözlərin yaranma yolları', 2),
(4, 'qrammatika', 'Şəkilçi növləri', 'Sözdəyişdirici və sözyaradıcı şəkilçilər', 2),
(4, 'qrammatika', 'Leksik məna və terminlər', 'Elmi terminlər, peşə sözləri', 2),
(4, 'qrammatika', 'Frazeologizmlər', 'Sabit söz birləşmələri, mənası və istifadəsi', 2),
(4, 'qrammatika', 'Mübtəda və xəbər', 'Cümlənin baş üzvləri, tapma üsulları', 3),
(4, 'qrammatika', 'Sadə cümlə', 'Bir mübtəda-xəbər qrupu olan cümlələr', 2),
(4, 'qrammatika', 'Mürəkkəb cümlə (giriş)', 'İki və daha çox sadə cümlədən ibarət cümlə', 2),
(4, 'qrammatika', 'Zərf anlayışı', 'Hərəkətin yerini, vaxtını, tərzini bildirən sözlər', 2),
(4, 'qrammatika', 'Qoşma anlayışı', 'Sözlər arasında əlaqə yaradan köməkçi sözlər', 2),
(4, 'oxu', 'Dərin oxu strategiyaları', 'Sual vermə, proqnozlaşdırma, vizuallaşdırma', 3),
(4, 'oxu', 'Tənqidi oxu', 'Müəllifin fikirini qiymətləndirmə, öz rəyi', 2),
(4, 'oxu', 'Cədvəl və diaqramdan məlumat alma', 'Qrafik məlumat mənbələrini oxuma', 2),
(4, 'oxu', 'İstinad mənbələri', 'Ensiklopediya, internet, kitabxana resursları', 2),
(4, 'oxu', 'Mövzu və ideya', 'Mətnin mövzusunu və əsas ideyasını müəyyən etmə', 2),
(4, 'yazi', 'İnşa yazma: mühakimə', 'Fikir irəli sürmə, əsaslandırma, nəticə', 3),
(4, 'yazi', 'Referat yazma əsasları', 'Mənbədən məlumat toplayıb yazma', 2),
(4, 'yazi', 'Atalar sözü ilə inşa', 'Atalar sözünü açıqlayan inşa yazma', 2),
(4, 'yazi', 'Rəy yazma', 'Oxuduğu kitab haqqında rəy yazma', 2),
(4, 'yazi', 'Yaradıcı yazı', 'Fantaziya, alternativ son, şeir yazmağa cəhd', 2),
(4, 'danisiq', 'Debat əsasları', 'Mövzu üzrə lehinə/əleyhinə fikir bildirmə', 2),
(4, 'danisiq', 'Təqdimat hazırlamaq', 'Mövzu seçmə, plan qurma, şifahi təqdimat', 2),
(4, 'danisiq', 'İntervyu aparmaq', 'Müsahibə planı qurmaq, suallar hazırlamaq', 2),
(4, 'danisiq', 'Dinləmə və qeyd alma', 'Dinlənilən mətndən əsas fikirləri qeyd etmə', 2),
(4, 'edebiyyat', 'Nizami Gəncəvi (giriş)', 'Nizaminin həyatı və yaradıcılığına giriş', 2),
(4, 'edebiyyat', 'Nəsimi yaradıcılığı (giriş)', 'İmadəddin Nəsiminin həyatı və şeirləri', 2),
(4, 'edebiyyat', 'Xalq mahnıları', 'Azərbaycan xalq mahnılarının mətni və mənası', 2),
(4, 'edebiyyat', 'Aşıq yaradıcılığı', 'Aşıq Ələsgər, Aşıq Pəri yaradıcılığına giriş', 2),
(4, 'edebiyyat', 'Hekayə janrı', 'Hekayənin quruluşu: giriş, əsas hissə, nəticə', 2),
(4, 'edebiyyat', 'Müqayisəli ədəbi təhlil (giriş)', 'İki əsərin müqayisəsi: mövzu, obrazlar', 2),
(4, 'edebiyyat', 'Kitab təqdimatı', 'Sevimli kitabın sinif qarşısında təqdim edilməsi', 2);

-- ═══════════════════════════════════════════════
-- 5-Cİ SİNİF (35 mövzu)
-- ═══════════════════════════════════════════════
INSERT INTO azdili_movzular (sinif, saha, movzu_adi, movzu_izahi, saat_sayi) VALUES
(5, 'qrammatika', 'Fonetika: səs sistemi', 'Sait və samitlərin təsnifatı, ahəng qanunu', 3),
(5, 'qrammatika', 'Fonetik təhlil', 'Sözün səs tərkibinin təhlili', 2),
(5, 'qrammatika', 'Leksikologiya', 'Sözün leksik və qrammatik mənası, omonimlər', 2),
(5, 'qrammatika', 'Söz yaradıcılığı üsulları', 'Morfoloji və sintaktik söz yaradıcılığı', 2),
(5, 'qrammatika', 'İsim: kateqoriyaları', 'Xüsusi/ümumi, tək/cəm, mənsubiyyət, hal', 3),
(5, 'qrammatika', 'Sifət növləri', 'Keyfiyyət, nisbi sifətlər, dərəcələri', 2),
(5, 'qrammatika', 'Say növləri', 'Miqdar, sıra, kəsr, qeyri-müəyyən say', 2),
(5, 'qrammatika', 'Əvəzlik növləri', 'Şəxs, işarə, sual, qeyri-müəyyən əvəzliklər', 2),
(5, 'qrammatika', 'Fel: təsirli və təsirsiz', 'Felin əsas kateqoriyası: təsirli/təsirsiz fellər', 2),
(5, 'qrammatika', 'Felin zamanları (dərinləşdirmə)', 'Keçmiş zamanın növləri, nəqli keçmiş, şühudi keçmiş', 2),
(5, 'qrammatika', 'Sintaksis əsasları', 'Söz birləşməsi, cümlə üzvləri, cümlə sxemləri', 3),
(5, 'qrammatika', 'Tamamlıq', 'Vasitəsiz və vasitəli tamamlıq', 2),
(5, 'qrammatika', 'Təyin və zərflik', 'Cümlənin ikinci dərəcəli üzvləri', 2),
(5, 'oxu', 'PISA oxu: məlumat alma', 'Mətndən konkret məlumatı tapma texnikası', 2),
(5, 'oxu', 'PISA oxu: şərh etmə', 'Mətndəki gizli mənanı şərh etmə', 2),
(5, 'oxu', 'PISA oxu: qiymətləndirmə', 'Mətnin forması və məzmunu haqqında rəy bildirmə', 2),
(5, 'oxu', 'Çoxmənbəli oxu', 'İki fərqli mənbədən oxuma, müqayisə etmə', 2),
(5, 'oxu', 'Mətndə arqument tapmaq', 'Müəllifin əsas arqumentini müəyyən etmə', 2),
(5, 'yazi', 'İnşa: mühakimə tipi', 'Tezis-arqument-nəticə strukturu ilə yazma', 3),
(5, 'yazi', 'İnşa: təsviri tip', 'Detallı təsvir, hiss-duyğu ifadəsi ilə yazma', 2),
(5, 'yazi', 'Esse yazma əsasları', 'Qısa fikir ifadəsi, əsaslandırma', 2),
(5, 'yazi', 'Annotasiya yazma', 'Kitab və ya məqalə haqqında qısa xülasə yazma', 2),
(5, 'yazi', 'Orfoqrafiya qaydaları', 'Ayrı və bitişik yazılan sözlər, tire istifadəsi', 2),
(5, 'danisiq', 'Diskussiya', 'Mövzu üzrə müzakirə aparmaq, dəlil gətirmək', 2),
(5, 'danisiq', 'Monoloji nitq', 'Hazırlıqlı şifahi çıxış, struktur', 2),
(5, 'danisiq', 'Dinləmə və analiz', 'Audio mətni dinləyib təhlil etmə', 2),
(5, 'edebiyyat', 'Nağıl janrı (təhlil)', 'Sehrli, məişət, heyvanlar haqqında nağıllar', 2),
(5, 'edebiyyat', 'Dastan janrı', '"Kitabi-Dədə Qorqud" əsərindən parçalar', 3),
(5, 'edebiyyat', 'Epik janr: hekayə', 'Hekayənin quruluşu, süjet xətti, konflikt', 2),
(5, 'edebiyyat', 'Lirik janr: şeir', 'Qafiyə, vəzn, bənd, bədii ifadə vasitələri', 2),
(5, 'edebiyyat', 'Bədii təsvir vasitələri (giriş)', 'Epitet, bənzətmə, metafora anlayışları', 2),
(5, 'edebiyyat', 'M.Ə.Sabir yaradıcılığı', 'Satirik şeirlər, "Hophopnamə"dən seçmələr', 2),
(5, 'edebiyyat', 'A.Səhhət yaradıcılığı', 'Abbas Səhhətin uşaq şeirləri', 2),
(5, 'edebiyyat', 'C.Cabbarlı (giriş)', 'Cəfər Cabbarlının həyatı, dramaturgiyaya giriş', 2),
(5, 'edebiyyat', 'Ədəbi portret', 'Yazıçı/şair haqqında əsas məlumat toplamaq', 2);

-- ═══════════════════════════════════════════════
-- 6-CI SİNİF (33 mövzu)
-- ═══════════════════════════════════════════════
INSERT INTO azdili_movzular (sinif, saha, movzu_adi, movzu_izahi, saat_sayi) VALUES
(6, 'qrammatika', 'Leksik tərkib', 'Ümumişlək və məhdud dairədə işlənən sözlər', 2),
(6, 'qrammatika', 'Alınma sözlər', 'Ərəb, fars, rus, Avropa mənşəli alınmalar', 2),
(6, 'qrammatika', 'Arxaizmlər və neologizmlər', 'Köhnəlmiş və yeni yaranan sözlər', 2),
(6, 'qrammatika', 'Frazeologiya', 'Frazeoloji birləşmələr, mənşəyi və istifadəsi', 2),
(6, 'qrammatika', 'Söz birləşməsi növləri', 'İdarə, uzlaşma, yanaşma əlaqələri', 3),
(6, 'qrammatika', 'Cümlə üzvləri (dərinləşdirmə)', 'Mübtəda, xəbər, tamamlıq, təyin, zərflik', 3),
(6, 'qrammatika', 'Xəbərin növləri', 'Feli xəbər, ismi xəbər', 2),
(6, 'qrammatika', 'Cümlənin məqsəd növləri', 'Nəqli, sual, nida, əmr cümlələri', 2),
(6, 'qrammatika', 'Cümlənin intonasiya növləri', 'Bəyan, sual, nida intonasiyası', 2),
(6, 'qrammatika', 'Həmcins üzvlər (giriş)', 'Eyni cümlə üzvü vəzifəsində olan sözlər', 2),
(6, 'oxu', 'Analitik oxu', 'Mətni dərindən təhlil etmə, müəllif mövqeyi', 3),
(6, 'oxu', 'İnferensal oxu', 'Mətndən çıxarımlar etmə, gizli məna', 2),
(6, 'oxu', 'Sənədli mətn oxusu', 'Qaydalar, təlimatlar, rəsmi sənədlər', 2),
(6, 'oxu', 'Media mətni oxusu', 'Qəzet məqaləsi, internet mətni təhlili', 2),
(6, 'yazi', 'Təhlili inşa', 'Ədəbi əsərin təhlilini yazma', 3),
(6, 'yazi', 'Rəsmi məktub', 'Ərizə, təqdimat məktubu, şikayət yazma', 2),
(6, 'yazi', 'Xəbər yazma', 'Hadisə haqqında qısa xəbər formatında yazma', 2),
(6, 'yazi', 'Yaradıcı hekayə', 'Əsas konflikt ətrafında hekayə yazma', 2),
(6, 'danisiq', 'Təqdimat bacarıqları', 'Vizual materiallarla təqdimat hazırlamaq', 2),
(6, 'danisiq', 'Debat', 'Mövzu üzrə formal debat qaydaları', 2),
(6, 'danisiq', 'Dramatizasiya', 'Ədəbi mətni səhnələşdirmə, rol bölgüsü', 2),
(6, 'edebiyyat', 'Nizami Gəncəvi: "Xəmsə"', '"Leyli və Məcnun", "Xosrov və Şirin" əsərlərindən parçalar', 3),
(6, 'edebiyyat', 'Xaqani Şirvani', 'Xaqaninin həyatı və qəsidələri', 2),
(6, 'edebiyyat', 'Xalq ədəbiyyatı: bayatılar', 'Bayatının quruluşu, növləri, ana mövzusu', 2),
(6, 'edebiyyat', 'Xalq ədəbiyyatı: laylalar', 'Laylaların funksiyası, bədii xüsusiyyətləri', 2),
(6, 'edebiyyat', 'Aşıq Ələsgər yaradıcılığı', 'Aşıq Ələsgərin qoşmaları və gəraylıları', 2),
(6, 'edebiyyat', 'Şah İsmayıl Xətai', 'Xətainin şeirləri və dövlətçilik fəaliyyəti', 2),
(6, 'edebiyyat', 'Məhsəti Gəncəvi', 'Məhsətinin rübailəri, qadın şair kimi rolu', 2),
(6, 'edebiyyat', 'Bədii təsvir vasitələri', 'Metafora, metonimiya, sinekdoxa, alleqoriya', 2),
(6, 'edebiyyat', 'Obraz sistemi', 'Əsas və ikinci dərəcəli obrazlar, xarakter inkişafı', 2),
(6, 'edebiyyat', 'Kompozisiya təhlili', 'Süjetin quruluşu: ekspozisiya, kulminasiya, çözüm', 2),
(6, 'edebiyyat', 'Ədəbi cərəyanlar (giriş)', 'Klassisizm, romantizm, realizm anlayışları', 2),
(6, 'edebiyyat', 'Yaradıcı layihə: ədəbi jurnal', 'Sinif ədəbi jurnalı hazırlamaq', 2);

-- ═══════════════════════════════════════════════
-- 7-Cİ SİNİF (33 mövzu)
-- ═══════════════════════════════════════════════
INSERT INTO azdili_movzular (sinif, saha, movzu_adi, movzu_izahi, saat_sayi) VALUES
(7, 'qrammatika', 'Felin şəkilləri', 'Əmr, arzu, şərt, xəbər, vacib, lazım şəkilləri', 3),
(7, 'qrammatika', 'Felin növləri', 'Məlum, məchul, qayıdış, icbar, qarşılıq-birgə növlər', 2),
(7, 'qrammatika', 'Modal sözlər', 'Mütləq, bəlkə, güman ki — danışanın münasibəti', 2),
(7, 'qrammatika', 'Qoşmalar', 'Qrammatik qoşmalar: ilə, üçün, kimi, haqqında', 2),
(7, 'qrammatika', 'Bağlayıcılar', 'Tabesizlik və tabelilik bağlayıcıları', 2),
(7, 'qrammatika', 'Ədatlar', 'Sual, əmr, güclləndirmə, məhdudlaşdırma ədatları', 2),
(7, 'qrammatika', 'Nidalar', 'Hiss-həyəcan bildirən sözlər', 1),
(7, 'qrammatika', 'Tabeli mürəkkəb cümlə', 'Baş və budaq cümlə, bağlayıcı vasitələr', 3),
(7, 'qrammatika', 'Tabesiz mürəkkəb cümlə', 'İştirak, ardıcıllıq, aydınlaşdırma əlaqəli cümlələr', 3),
(7, 'qrammatika', 'Vasitəsiz nitq', 'Vasitəsiz nitqin durğu işarələri', 2),
(7, 'qrammatika', 'Vasitəli nitq', 'Vasitəsiz nitqin vasitəli nitqə çevrilməsi', 2),
(7, 'oxu', 'Elmi-kütləvi mətn oxusu', 'Elmi mətnləri başa düşmə, terminologiya', 2),
(7, 'oxu', 'Publisistik mətn oxusu', 'Məqalə, müsahibə, reportaj təhlili', 2),
(7, 'oxu', 'Rəqəmsal oxu', 'Onlayn mənbələrin etibarlılığını yoxlama', 2),
(7, 'yazi', 'Arqumentativ esse', 'Tezis-dəlil-nəticə modeli ilə esse yazma', 3),
(7, 'yazi', 'Reportaj yazma', 'Hadisə haqqında reportaj formatında yazma', 2),
(7, 'yazi', 'Xülasə və annotasiya', 'Elmi və bədii mətnin xülasəsi', 2),
(7, 'yazi', 'CV və motivasiya məktubu', 'Şəxsi təqdimat sənədləri hazırlamaq', 2),
(7, 'danisiq', 'Panel müzakirə', 'Bir neçə mütəxəssisin iştirakı ilə müzakirə formatı', 2),
(7, 'danisiq', 'Şifahi təqdimat (qabaqcıl)', 'Tədqiqat nəticəsini şifahi təqdim etmə', 2),
(7, 'edebiyyat', 'Füzuli yaradıcılığı', 'Məhəmməd Füzulinin qəzəlləri, "Leyli və Məcnun"', 3),
(7, 'edebiyyat', 'Şah İsmayıl Xətai: divan şeirləri', 'Xətainin lirik şeirləri, vətən mövzusu', 2),
(7, 'edebiyyat', '"Koroğlu" eposu', 'Eposun süjeti, Koroğlu obrazı, igidlik mövzusu', 3),
(7, 'edebiyyat', 'M.P.Vaqif yaradıcılığı', 'Molla Pənah Vaqifin qoşmaları, realist üslub', 2),
(7, 'edebiyyat', 'Dramaturgiya (giriş)', 'Dram janrının xüsusiyyətləri, komediya və faciə', 2),
(7, 'edebiyyat', 'Sətiraltı məna', 'Ədəbi mətndə simvolizm və alleqoriya', 2),
(7, 'edebiyyat', 'Ədəbi tənqid əsasları', 'Əsər haqqında tənqidi rəy yazmaq', 2),
(7, 'edebiyyat', 'Müqayisəli analiz: Şərq-Qərb', 'Şərq və Qərb ədəbiyyatının müqayisəsi', 2),
(7, 'edebiyyat', 'Poeziya gecəsi layihəsi', 'Sinif poeziya gecəsi hazırlamaq və keçirmək', 2),
(7, 'edebiyyat', 'Q.Zakir yaradıcılığı', 'Qasım bəy Zakirin satirik şeirləri', 2),
(7, 'edebiyyat', 'Klassik qəzəl forması', 'Qəzəlin quruluşu: mətlə, beyt, məqtə', 2),
(7, 'edebiyyat', 'Mövzu və ideya təhlili', 'Əsərin mövzusu və ideyasını dərindən təhlil etmə', 2),
(7, 'edebiyyat', 'Ədəbi terminlər lüğəti', 'Əsas ədəbi terminləri öyrənmə və tətbiq etmə', 2);

-- ═══════════════════════════════════════════════
-- 8-Cİ SİNİF (33 mövzu)
-- ═══════════════════════════════════════════════
INSERT INTO azdili_movzular (sinif, saha, movzu_adi, movzu_izahi, saat_sayi) VALUES
(8, 'qrammatika', 'Cümlə üzvlərinin ifadə vasitələri', 'Hər cümlə üzvünün hansı nitq hissəsi ilə ifadəsi', 3),
(8, 'qrammatika', 'Xitab', 'Xitabın cümlədəki yeri, durğu işarələri', 2),
(8, 'qrammatika', 'Ara söz və ara cümlə', 'Ara sözlərin növləri, cümlədəki rolu', 2),
(8, 'qrammatika', 'Əlavə', 'Əlavənin cümlədəki vəzifəsi, durğu işarələri', 2),
(8, 'qrammatika', 'Həmcins üzvlər', 'Həmcins üzvlər, ümumiləşdirici söz', 3),
(8, 'qrammatika', 'Durğu işarələri (dərinləşdirmə)', 'Tire, qoşa nöqtə, nöqtəli vergül, dırnaq işarəsi', 3),
(8, 'qrammatika', 'Söz sırası', 'Azərbaycan dilində söz sırası, inversiya', 2),
(8, 'qrammatika', 'Elliptik cümlələr', 'Buraxılmış üzvlü cümlələr', 2),
(8, 'qrammatika', 'Mürəkkəb cümlə (dərinləşdirmə)', 'Qarışıq tipli mürəkkəb cümlələr', 2),
(8, 'oxu', 'Elmi mətn analizi', 'Elmi üslubun xüsusiyyətləri, terminologiya', 2),
(8, 'oxu', 'Tənqidi oxu (qabaqcıl)', 'Müəllifin mövqeyini dəlillərlə müdafiə/təkzib etmə', 2),
(8, 'oxu', 'Hüquqi mətn oxusu', 'Qanun, nizamnamə, müqavilə mətnlərini başa düşmə', 2),
(8, 'oxu', 'Rəqəmsal savadlılıq', 'Fake news tanıma, mənbə yoxlama, media savadlılığı', 2),
(8, 'yazi', 'Tədqiqat işi (giriş)', 'Kiçik tədqiqat: mövzu, mənbə, nəticə yazma', 3),
(8, 'yazi', 'Analitik esse', 'Problemi təhlil edən, həll təklif edən esse', 2),
(8, 'yazi', 'Rəsmi yazışma', 'İşgüzar yazışma qaydaları, e-mail mədəniyyəti', 2),
(8, 'yazi', 'Ədəbi təhlil inşası', 'Ədəbi əsərin strukturlu təhlilini yazma', 3),
(8, 'danisiq', 'İctimai çıxış', 'Auditoriya qarşısında strukturlu çıxış', 2),
(8, 'danisiq', 'Müzakirə moderatorluğu', 'Müzakirəni idarə etmə bacarığı', 2),
(8, 'edebiyyat', 'M.F.Axundzadə yaradıcılığı', '"Hekayəti-Müsyö Jordan", komediyalar', 3),
(8, 'edebiyyat', 'H.Zərdabi və maarifçilik', 'Həsən bəy Zərdabinin fəaliyyəti, "Əkinçi" qəzeti', 2),
(8, 'edebiyyat', 'S.Ə.Şirvani yaradıcılığı', 'Seyid Əzim Şirvaninin satirik şeirləri', 2),
(8, 'edebiyyat', 'N.Vəzirov dramaturgiyası', 'Nəcəf bəy Vəzirovun komediya və faciələri', 2),
(8, 'edebiyyat', 'Maarifçi realizm', 'XIX əsr Azərbaycan ədəbiyyatında realizm cərəyanı', 2),
(8, 'edebiyyat', 'Romantizm ədəbiyyatda', 'Romantizm cərəyanı, xüsusiyyətləri, nümayəndələri', 2),
(8, 'edebiyyat', 'Satirik ədəbiyyat', 'Satira janrı, "Molla Nəsrəddin" jurnalı', 2),
(8, 'edebiyyat', 'İnşa: ədəbi obraz təhlili', 'Ədəbi obrazın xarakterini dərindən təhlil etmə', 2),
(8, 'edebiyyat', 'Dramatik əsər təhlili', 'Dram əsərinin xüsusi təhlil üsulları', 2),
(8, 'edebiyyat', 'Tarixi roman janrı (giriş)', 'Tarixi mövzuda yazılmış romanlar, fakt və bədiilik', 2),
(8, 'edebiyyat', 'Ədəbi diskussiya', 'Ədəbi əsər üzrə sinif diskussiyası keçirmə', 2),
(8, 'edebiyyat', 'Layihə: ədəbi xəritə', 'Azərbaycan ədəbi xəritəsini hazırlamaq', 2),
(8, 'edebiyyat', 'M.Ə.Sabir: "Hophopnamə"', 'Sabirin ictimai satirası, şeirlərin təhlili', 2),
(8, 'edebiyyat', 'Ədəbi dövrləşdirmə', 'Azərbaycan ədəbiyyatının dövrləri: qədim, orta, yeni', 2);

-- ═══════════════════════════════════════════════
-- 9-CU SİNİF (33 mövzu)
-- ═══════════════════════════════════════════════
INSERT INTO azdili_movzular (sinif, saha, movzu_adi, movzu_izahi, saat_sayi) VALUES
(9, 'qrammatika', 'Mürəkkəb sintaktik bütöv', 'Bir neçə cümlədən ibarət tematik vahid', 3),
(9, 'qrammatika', 'Mətn dilçiliyi', 'Mətnin əlamətləri: bütövlük, bitkinlik, əlaqəlilik', 2),
(9, 'qrammatika', 'Funksional üslublar', 'Beş üslub: bədii, elmi, publisistik, rəsmi, danışıq', 3),
(9, 'qrammatika', 'Bədii üslub', 'Bədii üslubun xüsusiyyətləri, dil vasitələri', 2),
(9, 'qrammatika', 'Publisistik üslub', 'Publisistik üslubun xüsusiyyətləri, janrları', 2),
(9, 'qrammatika', 'Elmi üslub', 'Elmi üslubun xüsusiyyətləri, terminologiya', 2),
(9, 'qrammatika', 'Rəsmi-işgüzar üslub', 'Sənəd dili, rəsmi üslubun xüsusiyyətləri', 2),
(9, 'qrammatika', 'Danışıq üslubu', 'Şifahi nitqin xüsusiyyətləri, jarqonlar', 2),
(9, 'qrammatika', 'Mətn redaktəsi', 'Üslub səhvlərini tapma və düzəltmə', 2),
(9, 'oxu', 'Akademik oxu', 'Elmi məqalə, tezis, referat oxuma texnikası', 3),
(9, 'oxu', 'Fəlsəfi mətn oxusu', 'Mücərrəd fikirləri başa düşmə, interpretasiya', 2),
(9, 'oxu', 'Müqayisəli mənbə analizi', 'Eyni mövzuda müxtəlif mənbələrin müqayisəsi', 2),
(9, 'yazi', 'Tədqiqat işi', 'Tədqiqat sualı, hipoteza, məlumat toplama, nəticə', 3),
(9, 'yazi', 'Resenziya yazma', 'Kitab, film, tamaşa haqqında resenziya', 2),
(9, 'yazi', 'Problemli esse', 'İctimai problem üzrə esse: tezis, dəlil, nəticə', 2),
(9, 'yazi', 'Layihə təqdimatı yazısı', 'Layihə təklifini yazılı formada təqdim etmə', 2),
(9, 'danisiq', 'Elmi konfrans simulyasiyası', 'Kiçik elmi məruzə hazırlama və təqdim etmə', 2),
(9, 'danisiq', 'Ritorika əsasları', 'İnandırıcı nitq qurmaq: etos, patos, loqos', 2),
(9, 'edebiyyat', 'C.Məmmədquluzadə yaradıcılığı', '"Danabaş kəndinin əhvalatları", "Ölülər" pyesi', 3),
(9, 'edebiyyat', 'Ü.Hacıbəyov yaradıcılığı', '"Arşın mal alan", "Leyli və Məcnun" operası', 2),
(9, 'edebiyyat', 'A.Səhhət yaradıcılığı', 'Abbas Səhhətin lirik şeirləri, tərcüməçilik fəaliyyəti', 2),
(9, 'edebiyyat', 'H.Cavid yaradıcılığı', 'Hüseyn Cavidin romantik dramları', 2),
(9, 'edebiyyat', 'M.Hadi yaradıcılığı', 'Məhəmməd Hadinin romantik şeirləri', 2),
(9, 'edebiyyat', '"Molla Nəsrəddin" jurnalı', 'Jurnalın rolu, karikaturaları, satirik yazıları', 2),
(9, 'edebiyyat', 'XX əsr Azərbaycan ədəbiyyatı', 'İctimai-siyasi mühit və ədəbiyyata təsiri', 2),
(9, 'edebiyyat', 'Realizm cərəyanı (dərinləşdirmə)', 'Tənqidi realizm, xüsusiyyətləri, nümayəndələri', 2),
(9, 'edebiyyat', 'Müstəqillik dövrü ədəbiyyatı (giriş)', 'Müstəqillik sonrası ədəbi proseslər', 2),
(9, 'edebiyyat', 'Ədəbi esse yazma', 'Ədəbi mövzuda esse: ideyadan sona qədər', 2),
(9, 'edebiyyat', 'Dramatik əsər səhnələşdirmə', 'Dram əsərini sinif truppa ilə səhnəyə qoymaq', 2),
(9, 'edebiyyat', 'A.Şaiq "Köçərilərin Azərbaycana gəlməsi"', 'Maarifçi əsərin təhlili, ideya və obrazlar', 2),
(9, 'edebiyyat', 'Ədəbi tənqid yazma', 'Əsər haqqında tənqidi məqalə formatında yazma', 2);

-- ═══════════════════════════════════════════════
-- 10-CU SİNİF (33 mövzu)
-- ═══════════════════════════════════════════════
INSERT INTO azdili_movzular (sinif, saha, movzu_adi, movzu_izahi, saat_sayi) VALUES
(10, 'qrammatika', 'Dil tarixinə giriş', 'Azərbaycan dilinin mənşəyi, türk dilləri ailəsi', 2),
(10, 'qrammatika', 'Azərbaycan dilinin inkişaf mərhələləri', 'Qədim, orta əsrlər, yeni dövr dil inkişafı', 2),
(10, 'qrammatika', 'Dialektologiya', 'Dialektlər, ləhcələr, şivələr', 2),
(10, 'qrammatika', 'Ədəbi dil normaları', 'Orfoqrafik, orfoepik, leksik, qrammatik normalar', 3),
(10, 'qrammatika', 'Orfoqrafiya qaydaları (dərinləşdirmə)', 'Çətin orfoqrafik hallar, istisnalar', 2),
(10, 'qrammatika', 'Orfoepiya qaydaları', 'Düzgün tələffüz qaydaları, vurğu', 2),
(10, 'qrammatika', 'Etimologiya', 'Sözlərin mənşəyini araşdırma, dil tarixi', 2),
(10, 'qrammatika', 'Leksikoqrafiya', 'Lüğət növləri: izahlı, terminoloji, frazeoloji, etimoloji', 2),
(10, 'oxu', 'Fəlsəfi-ədəbi mətn', 'Dərin mənalı əsərlərin interpretasiyası', 2),
(10, 'oxu', 'Tədqiqat ədəbiyyatı oxusu', 'Ədəbiyyatşünaslıq əsərlərini oxuma', 2),
(10, 'oxu', 'Dünya ədəbiyyatından nümunələr (oxu)', 'Şekspir, Dostoyevski, Heminquey əsərlərindən parçalar', 2),
(10, 'yazi', 'Elmi məqalə yazma əsasları', 'Elmi məqalənin strukturu, istinadlar', 3),
(10, 'yazi', 'Ədəbi-tənqidi esse', 'Ədəbi əsər haqqında tənqidi esse yazma', 2),
(10, 'yazi', 'Analitik yazı', 'Problemi təhlil edən, çözüm təklif edən yazı', 2),
(10, 'danisiq', 'İctimai nitq (qabaqcıl)', 'Böyük auditoriya qarşısında nitq, ritorik fiqurlar', 2),
(10, 'danisiq', 'Akademik müzakirə', 'Akademik formatda müzakirə, dəlil-əsas gətirmə', 2),
(10, 'edebiyyat', 'S.Vurğun yaradıcılığı', '"Vaqif" dramı, lirik şeirlər, vətən mövzusu', 3),
(10, 'edebiyyat', 'R.Rza yaradıcılığı', 'Rəsul Rzanın sərbəst şeirləri, novatorluğu', 2),
(10, 'edebiyyat', 'M.Müşfiq yaradıcılığı', 'Mikayıl Müşfiqin lirik şeirləri, repressiya mövzusu', 2),
(10, 'edebiyyat', 'B.Vahabzadə yaradıcılığı', 'Bəxtiyar Vahabzadənin fəlsəfi şeirləri, "Gülüstan" poeması', 3),
(10, 'edebiyyat', 'İ.Əfəndiyev yaradıcılığı', 'İlyas Əfəndiyevin romanları və dramları', 2),
(10, 'edebiyyat', 'Mir Cəlal yaradıcılığı', 'Mir Cəlalın hekayə və romanları', 2),
(10, 'edebiyyat', 'Sovet dövrü Azərbaycan ədəbiyyatı', 'Sovet ideologiyası və ədəbiyyat, senzura', 2),
(10, 'edebiyyat', 'Dünya ədəbiyyatı: Şekspir', 'Şekspirin sonetləri, "Hamlet" əsəri', 2),
(10, 'edebiyyat', 'Dünya ədəbiyyatı: Puşkin, Lermontov', 'Rus klassiklərinin Azərbaycan ədəbiyyatına təsiri', 2),
(10, 'edebiyyat', 'Müqayisəli ədəbi təhlil (dərin)', 'İki fərqli dövrün əsərlərinin müqayisəsi', 2),
(10, 'edebiyyat', 'Ədəbi portret yazma', 'Yazıçı/şairin həyat və yaradıcılıq portreti', 2),
(10, 'edebiyyat', 'Tədqiqat layihəsi: ədəbi dövr', 'Seçilmiş ədəbi dövr haqqında tədqiqat işi', 3),
(10, 'edebiyyat', 'Ç.Aytmatov yaradıcılığı', 'Çingiz Aytmatovun əsərləri, humanizm mövzusu', 2),
(10, 'edebiyyat', 'Ədəbi-tənqidi fikir tarixi', 'Azərbaycan ədəbi tənqidinin inkişaf mərhələləri', 2),
(10, 'edebiyyat', 'Mühacirət ədəbiyyatı', 'Mühacirətdə yaranan Azərbaycan ədəbiyyatı', 2),
(10, 'edebiyyat', 'Ədəbi cərəyanlar müqayisəsi', 'Klassisizm, romantizm, realizm, modernizm müqayisəsi', 2),
(10, 'edebiyyat', 'Layihə: ədəbi gecə', 'Sinif ədəbi gecəsi hazırlamaq və keçirmək', 2);

-- ═══════════════════════════════════════════════
-- 11-Cİ SİNİF (33 mövzu)
-- ═══════════════════════════════════════════════
INSERT INTO azdili_movzular (sinif, saha, movzu_adi, movzu_izahi, saat_sayi) VALUES
(11, 'qrammatika', 'Üslubiyyat', 'Funksional üslubların dərin təhlili, üslub seçimi', 3),
(11, 'qrammatika', 'Nitq mədəniyyəti', 'Nitq normaları, nitq səhvləri, düzgün danışıq', 2),
(11, 'qrammatika', 'Ritorika', 'Natiqlik sənəti, nitqin quruluşu, inandırma üsulları', 3),
(11, 'qrammatika', 'Mübahisə və diskussiya mədəniyyəti', 'Elmi mübahisə qaydaları, etik normalar', 2),
(11, 'qrammatika', 'İctimai nitq hazırlığı', 'Tezis, plan, vizual material, çıxış texnikası', 2),
(11, 'qrammatika', 'KİV-in dili', 'Kütləvi informasiya vasitələrinin dil xüsusiyyətləri', 2),
(11, 'qrammatika', 'Reklam dili', 'Reklam mətnlərinin dil xüsusiyyətləri, manipulyasiya', 2),
(11, 'qrammatika', 'Dil siyasəti', 'Azərbaycan dili dövlət dili kimi, dil qanunvericiliyi', 2),
(11, 'qrammatika', 'Dilçilik elminin sahələri', 'Fonetika, leksikologiya, morfologiya, sintaksis xülasə', 2),
(11, 'oxu', 'Akademik mətn oxusu', 'Dissertasiya, monoqrafiya parçalarını oxuma', 2),
(11, 'oxu', 'Kritik media savadlılığı', 'Dezinformasiyanı tanımaq, fakt-yoxlama', 2),
(11, 'oxu', 'Fəlsəfi esse oxusu', 'Dərin fəlsəfi mətnlərin interpretasiyası', 2),
(11, 'yazi', 'Bitirmə inşası', 'Geniş həcmli, strukturlu inşa yazma', 3),
(11, 'yazi', 'Elmi-tədqiqat işi', 'Tam tədqiqat formatı: giriş, metodologiya, nəticə', 3),
(11, 'yazi', 'Publisistik yazı', 'Məqalə, felyeton, oçerk yazma', 2),
(11, 'yazi', 'Portfolio hazırlama', 'Fərdi yazı portfoliosu: seçmə, redaktə, təqdimat', 2),
(11, 'danisiq', 'Formal debat yarışması', 'Rəsmi debat qaydaları ilə yarışma keçirmə', 2),
(11, 'danisiq', 'TED formatında çıxış', 'Qısa, təsirli ictimai çıxış hazırlamaq', 2),
(11, 'edebiyyat', 'Müasir Azərbaycan ədəbiyyatı', 'Müstəqillik dövrü ədəbi prosesləri', 2),
(11, 'edebiyyat', 'Kamal Abdulla yaradıcılığı', '"Yarımçıq əlyazma" romanı, postmodernizm', 2),
(11, 'edebiyyat', 'Afaq Məsud yaradıcılığı', 'Müasir nəsr, qadın ədəbiyyatı', 2),
(11, 'edebiyyat', 'Azərbaycan dramaturgiyası', 'XX-XXI əsr Azərbaycan dramaturgiyasının inkişafı', 2),
(11, 'edebiyyat', 'Ernest Heminquey yaradıcılığı', '"Qoca və dəniz", "aysberq prinsipi"', 2),
(11, 'edebiyyat', 'Çingiz Aytmatov (dərinləşdirmə)', '"Gün var əsrə bərabər", humanizm fəlsəfəsi', 2),
(11, 'edebiyyat', 'Dünya ədəbiyyatı: modernizm', 'Kafka, Kamyu, Sartr əsərlərindən seçmələr', 2),
(11, 'edebiyyat', 'Ədəbiyyat və fəlsəfə', 'Ədəbiyyatda ekzistensializm, absurd, humanizm', 2),
(11, 'edebiyyat', 'Ədəbiyyat və kino', 'Ədəbi əsərlərin ekranlaşdırılması, müqayisə', 2),
(11, 'edebiyyat', 'Postmodern ədəbiyyat', 'Postmodernizmin xüsusiyyətləri, intertekstuallıq', 2),
(11, 'edebiyyat', 'Ədəbi kanon müzakirəsi', 'Hansı əsərlər klassikdir? Kanon necə formalaşır?', 2),
(11, 'edebiyyat', 'Bitirmə layihəsi: ədəbi tədqiqat', 'Seçilmiş müəllif/əsər haqqında geniş tədqiqat', 4),
(11, 'edebiyyat', 'Dünya ədəbiyyatı: Markes', 'Qabriel Qarsia Markesin sehrli realizmi', 2),
(11, 'edebiyyat', 'Müasir şeir', 'Müasir Azərbaycan şeirində yeni tendensiyalar', 2),
(11, 'edebiyyat', 'Ədəbi almanax layihəsi', 'Sinif ədəbi almanaxı hazırlamaq', 3);
